language: generic
sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - IMAGE_NAME=$DOCKER_USER/svn-server

script:
  - cd svn-server
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:travis-$TRAVIS_BUILD_NUMBER

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

deploy:
  provider: script
  script: docker push $IMAGE_NAME
  