node {
  stage("git clone") {
    checkout scm
  }

  sh "git rev-parse HEAD > .git/commit-id"
  def commit_id = readFile('.git/commit-id').trim()
  println commit_id
  
  def app
  
  stage("docker build") {
    app = docker.build("hsudbrock/svn-server", "-f svn-server/Dockerfile .")
  }
  
  stage("docker publish") {
      docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
          app.push("${env.BUILD_NUMBER}")
          app.push("${commit_id}")
          app.push("latest")
      }
  }
}
